// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApVigh_5nSRQZM598WhUd21IId07mRQok',
    appId: '1:571759676990:web:b8290b207303aa05d60b6f',
    messagingSenderId: '571759676990',
    projectId: 'crud-6751e',
    authDomain: 'crud-6751e.firebaseapp.com',
    storageBucket: 'crud-6751e.appspot.com',
    measurementId: 'G-BJ4SS9E38C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYlJbUiof0pqobQMoeOQ8t8RvtzAL8tMg',
    appId: '1:571759676990:android:1cd81fe30909dedad60b6f',
    messagingSenderId: '571759676990',
    projectId: 'crud-6751e',
    storageBucket: 'crud-6751e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQDCv1_taNXxxkzaiEris-aEBeyh4DLo',
    appId: '1:571759676990:ios:032d7ca7b3c3aff2d60b6f',
    messagingSenderId: '571759676990',
    projectId: 'crud-6751e',
    storageBucket: 'crud-6751e.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHQDCv1_taNXxxkzaiEris-aEBeyh4DLo',
    appId: '1:571759676990:ios:6b56defe119660d0d60b6f',
    messagingSenderId: '571759676990',
    projectId: 'crud-6751e',
    storageBucket: 'crud-6751e.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVigh_5nSRQZM598WhUd21IId07mRQok',
    appId: '1:571759676990:web:c8c37e5aa181d693d60b6f',
    messagingSenderId: '571759676990',
    projectId: 'crud-6751e',
    authDomain: 'crud-6751e.firebaseapp.com',
    storageBucket: 'crud-6751e.appspot.com',
    measurementId: 'G-5DXD33P60X',
  );

}